config/routes.rb
Rails.application.routes.draw do
  root "cocktails#index"

  resources :ingredients, only: [ :index, :new, :show, :create ]#, :create ]
  resources :cocktails, only: [ :index, :new, :show, :create, :update, :edit ] do
    resources :doses, only: [ :new, :create]

  end
  resources :doses, only: [:destroy ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  before_destroy :check_for_doses
  validates :name, uniqueness: true, presence: true

  def check_for_doses
    if doses.count > 0
      return false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
# app/controllers/restaurants_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :update, :edit]

  def index
    if search = params["search"]
      @cocktails = Cocktail.where("name ILIKE ?", "%#{search}%")
    else
      @cocktails = Cocktail.all
    end
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully created.' }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully updated.' }
        format.json { render :show, status: :ok, location: @cocktail }
      else
        format.html { render :edit }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    def cocktail_params
      params.require(:cocktail).permit(:name,:photo, :photo_cache)
    end
end

app/controllers/doses_controller.rb
# app/controllers/restaurants_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new
    @ingredients = Ingredient.all
  end

  def create
    @dose = Dose.new(dose_params)
  #  @dose.description = dose_params["description"]
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path
  end

  private

    def set_cocktail
      @cocktail = Cocktail.find(params[:cocktail_id])
    end

    def dose_params
      params.require(:dose).permit(:description, :ingredient_id)
    end
end

app/controllers/ingredients_controller.rb
# app/controllers/restaurants_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show]

  def index
    @ingredients = Ingredient.all
  end

  def show
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    def ingredient_params
      params.require(:ingredient).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, input_html: {class: "col-xs-12 col-md-10 col-md-offset-1 custom-input"} %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>
  <div class="center">
    <%= f.button :submit, class: "btn btn-success" %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Editing Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Show', @cocktail %> |
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<p id="notice"><%= notice %></p>

<div class="col-xs-12 col-md-10 col-md-offset-1 wrapper">
  <h1 class="center">About</h1>
        <%= image_tag "alex-tortue.jpg", class: "square col-md-6 col-xs-12" %>
        <%= image_tag "alex2.jpg", class: "square col-md-6 col-xs-12" %>

  <p>
    Alex Vaca likes Bitcoins of course! But also, he likes to drink and to make people drink since he is a little boy. From this passion, he decided to
    become a bar tender in Majorca, this beautiful paradisiac place in Spain full of authentic and local people.
  </p>
  <p>
    He is able to make 89 different cocktails and he knows more than 143 alcohols. So if he doesn't manage to become a Ruby developer or bitcoins expert, he still has a solid potential to make cocktails. Here you can discover some of his secrets...
  </p>



  <h1 class="center">Cocktails</h1>

  <div class="center" style="width:100%">
    <%= link_to 'New Cocktail', new_cocktail_path, class: "btn btn-danger" %>
    <%= link_to 'New Ingredient', new_ingredient_path, class: "btn btn-primary" %>
  </div>


  <% @cocktails.each do |cocktail| %>

    <div class="col-xs-12 col-md-6 ">
    <% if cocktail.photo? %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path cocktail.photo, height: 300, width: 400, crop: :fill %>');">
    <% else %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path "alex.jpg", height: 300, width: 400, crop: :fill %>');">
    <% end %>


        <div class="card-category">
          <%= cocktail.name %> (<%= cocktail.doses.count %> ingrédients)
          <%= link_to edit_cocktail_path(cocktail) do %>
            <i class="fa fa-pencil-square-o white" aria-hidden="true"></i>
          <% end %>

        </div>
        <div class="card-description">
          <h2>Ingrédients</h2>
          <% cocktail.doses.each do |dose| %>
            <li><%= dose.description %> de <%= dose.ingredient.name %></li>
          <% end %>
          <p>
            <%= link_to 'Show cocktail', cocktail, class: "btn btn-success" %>
            <%= link_to 'Add ingredient', new_cocktail_dose_path(cocktail), class: "btn btn-primary" %>
          </p>
        </div>
        <img class="card-user" src="https://i.skyrock.net/8961/4258961/pics/72820669.jpg">
      </div>
    </div>


  <% end %>

</div>

app/views/cocktails/new.html.erb
<div class="col-xs-12 col-md-6 col-md-offset-3">

  <div class="my-panel">
    <h1>New Cocktail</h1>

    <%= render 'form', cocktail: @cocktail %>

    <%= link_to 'Back', cocktails_path %>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="col-xs-12 col-sm-6 col-sm-offset-3">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cocktail.name %>
  <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>
</p>

<%= link_to 'Back', cocktails_path %>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.input :ingredient_id, collection: @ingredients%>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/doses/new.html.erb
<div class="col-xs-12 col-md-6 col-md-offset-3">

  <div class="my-panel">
    <h1>New Dose</h1>

    <%= render 'form',        dose: @dose, cocktail: @cocktail %>

    <%= link_to 'Back', cocktails_path %>
  </div>
</div>

app/views/ingredients/_form.html.erb
<%= simple_form_for(@ingredient) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, input_html: {class: "col-xs-12 col-md-10 col-md-offset-1 custom-input"} %>
  </div>
  <div class="center">
    <%= f.button :submit, class: "btn btn-success" %>
  </div>
<% end %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>


<div class="col-xs-12 col-md-6 col-md-offset-3 wrapper">
  <h1 class="center">Ingrédients</h1>

  <div class="center" style="width:100%">
    <%= link_to '+ New Ingredients', new_ingredient_path, class: "btn btn-danger" %>
  </div>


  <ul>
    <% @ingredients.each do |ingredient| %>
      <li> <%= ingredient.name %> </li>
    <% end %>
  </ul>
  <%= link_to 'Back to cocktails', cocktails_path %>
</div>

app/views/ingredients/new.html.erb
<div class="col-xs-12 col-md-6 col-md-offset-3">

  <div class="my-panel">
    <h1>New Ingredient</h1>

    <%= render 'form', ingredient: @ingredient %>

    <%= link_to 'Back', ingredients_path %>
  </div>
</div>

app/views/ingredients/show.html.erb
<div class="col-xs-12 col-sm-6 col-sm-offset-3">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<%= link_to 'Back', ingredients_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.jpg" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
        <form class="navbar-form" role="search" action="">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search cocktail..." name="search">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
        </form>
    <%= link_to "Cocktails", cocktails_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Ingredients", ingredients_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <a href="https://www.facebook.com/alex.vacca.146?fref=ts" class= "navbar-wagon-item navbar-wagon-link" ><i class="fa fa-facebook-square" aria-hidden="true"></i> Alex's facebook</a>
    <a href="https://www.instagram.com/vk.alexx/?hl=fr" class= "navbar-wagon-item navbar-wagon-link" ><i class="fa fa-instagram" aria-hidden="true"></i> Alex's Instagram</a>
    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "alex.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_searchform.html.erb
<%= simple_form_for() do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, input_html: {class: "col-xs-12 col-md-10 col-md-offset-1 custom-input"} %>

  </div>
  <div class="center">
    <%= f.button :submit, class: "btn btn-success" %>
  </div>
<% end %>